[project]
authors = ["igi-111"]
entry = "main.sw"
license = "Apache-2.0"
name = "perlin"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs" }
fixed_point = { git = "https://github.com/IGI-111/fixed_point.git" }
